#Help: https://docs.gitlab.com/ee/ci/yaml/
#Validation: https://gitlab.com/roleone/webapp/-/ci/lint
image: trion/ng-cli-karma

.node: &node
  image: node:latest
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
    - node_modules/

before_script:
    - npm i -g @angular/cli

stages:
  - build
  - test
  - deploy

#build_dev:
#  stage: build
#  environment:
#    name: dev
#  <<: *node
#  script:
#    - npm install
#    - npm run builddev

build_master:
  stage: build
  environment:
    name: production
  <<: *node
  script:
    - npm install
    - npm run buildprod
  only:
    - master

karma_test:
  image: trion/ng-cli-karma
  stage: test
  script:
    - rm ./package-lock.json
    - npm install
    - echo 'running tests with code coverage'
    - ./node_modules/@angular/cli/bin/ng test --watch=false --code-coverage
  artifacts:
    paths:
      - coverage/

coverage:
  image: alpine
  stage: deploy
  dependencies:
    - karma_test
  before_script:
    - echo 'deploying code coverage stats'
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days

#protactor_test:
#  stage: test
#  script:
#    - rm ./package-lock.json
#    - npm install
#    - ./node_modules/@angular/cli/bin/ng e2e --progress false --watch=false

deploy_firebase:
  stage: deploy
  environment:
    name: production
  <<: *node
  script:
    - npm install
    - npm run deploy
  only:
    - master
