.node: &node
  image: node:8.9
  before_script:
    - npm install
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
    - node_modules/

stages:
  - deploy

deploy_dev:
  stage: deploy
  environment:
    name: dev
  <<: *node
  script:
    - npm run build -- -e $CI_ENVIRONMENT_SLUG
    - npm run deploy
  only:
    - dev

deploy_production:
  stage: deploy
  environment:
    name: production
  <<: *node
  script:
    - npm run build -- -e $CI_ENVIRONMENT_SLUG
    - npm run deploy
  only:
    - master
