.node: &node
  image: node:latest
  before_script:
    - npm install
  cache:
    paths:
    - node_modules/

stages:
  - deploy

deploy_dev:
  stage: deploy
  environment:
    name: dev
  <<: *node
  script:
    - npm run deploy
  only:
    - dev

deploy_production:
  stage: deploy
  environment:
    name: production
  <<: *node
  script:
    - npm run buildprod 
    - npm run deploy
  only:
    - master
