#Help: https://docs.gitlab.com/ee/ci/yaml/
#Validation: https://gitlab.com/roleone/webapp/-/ci/lint
.node: &node
  image: node:latest
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  environment:
    name: dev
  <<: *node
  script:
    - npm install
    - npm run build

test_build:
  stage: test
  script:
    - npm install
    - ng test --progress false --single-run=true --watch=false
    - ng e2e --progress false --watch=false

deploy_production:
  stage: deploy
  environment:
    name: production
  <<: *node
  script:
    - npm install
    - npm run deploy
  only:
    - master
