# Help: https://docs.gitlab.com/ee/ci/yaml/
# Validation: https://gitlab.com/roleone/webapp/-/ci/lint

# The goal is to run the tests in a docker container. Because if you try running
# in just a node:latest container, it won’t work since Karma is looking for Chrome.
# Luckily someone has already done the hard work in solving that problem.
# A huge shout out to this docker container and it’s maintainer.
image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

before_script:
    - npm i -g @angular/cli
    - node -v
    - npm install

stages:
  - build
  - test
  - deploy

build_dev:
  stage: build
  environment:
    name: dev
  script:
    - npm run builddev
  only:
    - dev

build_master:
  stage: build
  environment:
    name: production
  script:
    - npm run buildprod
  only:
    - master

coverage:
  image: alpine
  stage: deploy
  dependencies:
    - karma_test
  before_script:
    - echo 'deploying code coverage stats'
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days

karma_test:
  image: trion/ng-cli-karma
  stage: test
  script:
    - rm ./package-lock.json
    - echo 'running tests with code coverage'
    - ng test --watch=false --code-coverage
  artifacts:
    paths:
      - coverage/

protactor_test:
  stage: test
  script:
    - rm ./package-lock.json
    - ng e2e --progress false --watch=false

#For final user tests
deploy_firebase_dev:
  stage: deploy
  environment:
    name: dev
  script:
    - npm run builddev
    - npm run deploy
  allow_failure: true
  only:
    - dev

#Production application
deploy_firebase_prod:
  stage: deploy
  environment:
    name: production
  script:
    - npm run buildprod
    - npm run deploy
  only:
    - master
